using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UniversityofContoso.Controllers
{
    public class ChatRoomController : Controller //Creates a Controller "ChatRoomController". //
    {
        // GET: /ChatRoom/
        public ActionResult SignalRChat() //This is required to get the chat feature which is implemented, in this app to run. //
        {
            return View(); //Shows a page (Renders a chat page Generated by the "SignalRChat" Object.) //
        }
    }
}